version: 2

exposures:  
  - name: product_funnel_dashboard
    label: Product funnel visualization using BI tool
    type: dashboard
    maturity: medium
    description: Visualize product funnel performance through BI tool (Sigma)

    depends_on:
      - ref('fct_sessions_daily')

    owner:
      name: E D
      email: xxxx@gmail.com

    tags: ['bi-dashboard', 'product-funnel']
