version: 2

exposures:  
  - name: product_funnel_dashboard
    label: Product funnel visualization using BI tool
    type: dashboard
    maturity: medium
    description: >
        Models to facilitate product analytics by using BI tool to visualize
        daily funnel performance at user and product granularities through BI
        tool

    depends_on:
      - ref('fct_sessions_daily')

    owner:
      name: E D
      email: xxxx@gmail.com

    tags: ['bi-dashboard', 'product-funnel']
